### ISSUE TITLE
error handling in server

### ISSUE THREAD

**Issue by Jbarget** [FACN1/week5-hibas-angels#29]
https://github.com/FACN1/week5-hibas-angels/blob/master/src/handlers.js#L33

I imagine its something that you just didn't get round to but its really important to do more than just `console.log` the error.

If you are using a website and it looks like nothing is happening after you click a button, you'll tend to click the button again. But really the you need to know that something hasn't worked

**Comment by mattlub** [comment]
yep, agreed. we're sorting it (kind of dupe of #21)

**Comment by Jbarget** [comment]
ah soz, my fault
